### ISSUE TITLE
Help confirming driver bug in ChibiOS please.

### ISSUE THREAD

**Issue by ghost** [oresat/devsat#3]
I'm looking to confirm this before I hit the ChibiOS forums and ask there.

I think I have found a bug in the ChibiOS STM32 I2Cv2 address alignment logic. I have commented out the original code below. We should only shift the address iff we are in 10 bit address mode. The original code does the reverse. This is in the file:

```
.../Orsat/devsat/firmware/ChibiOS-RT/os/hal/ports/STM32/LLD/I2Cv2/hal_i2c_lld.c
```

This bug only seems to manifest if you are using 7 bit addresses and have an address with the highest bit index (6) set. Which of course with the LTC2990 chip, we do. (0x98...the address is bits [7:1]). You'll probably need to confirm this with the Reference manual for the stm32f0xxx. *Maybe I'm just lost in the weeds on this one.*

```
static void i2c_lld_set_address(I2CDriver *i2cp, i2caddr_t addr) {
  I2C_TypeDef *dp = i2cp->i2c;

  /* Address alignment depends on the addressing mode selected.*/
  // if ((i2cp->config->cr2 & I2C_CR2_ADD10) == 0U)
    // dp->CR2 = (uint32_t)addr << 1U;
  // else
    // dp->CR2 = (uint32_t)addr;

  /* Address alignment depends on the addressing mode selected.*/
  if ((i2cp->config->cr2 & I2C_CR2_ADD10) == 0U)
	dp->CR2 = (uint32_t)addr;
  else
	dp->CR2 = (uint32_t)addr << 1U;
}

```

Thanks!

**Comment by heliochronix** [comment]
We've determined that this is not a bug.

7-bit addressing modes shift the address bits left by 1 in order to facilitate the use of a R/W bit at the end. The data sheet for the LTC2990 specifies the address as a 8 bit hex value that incorporates this R/W bit for you, while most other data sheets only specify the 7 bit address. ChibiOS shifts the normal 7-bit address only when in 7-bit address mode, so it expects just the raw address bits and it will handle it accordingly.

As such, I've fixed the code to designate the LTC2990 address as a binary address (per the examples established for other I2C peripherals) and have set the ChibiOS submodule back to the upstream repository to keep up to date with the latest updates and bug fixes in ChibiOS.
